language: ruby

rvm:
  - 2.3.0
  - 2.4.0

sudo: false

gemfile:
  - gemfiles/rails_41.gemfile
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_50.gemfile

services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE zdm_test;'

script: 'bundle exec rake'
