language: ruby

rvm:
  - 2.4.3
  - 2.5.1

sudo: false

gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.2.gemfile

services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE zdm_test DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'

script: 'bundle exec rake'
